### ISSUE TITLE
删除多余代码

### ISSUE THREAD

**Issue by Belee05** [pyFigure/cc_django#2]
路径：config ->product.py
原代码
```
{ % - if cookiecutter.use_celery.lower() == 'y' %}
CELERY_BROKER_URL = env.get('CELERY_BROKER_URL')
{ % - endif %}
```

修改后代码
```
CELERY_BROKER_URL = env.get('CELERY_BROKER_URL')
```

**Comment by ppsite** [comment]
{%- if cookiecutter.use_celery.lower() == 'y' %}
CELERY_BROKER_URL = env.get('CELERY_BROKER_URL')
{%- endif %}

去掉两个空格即可解决；已在提交代码修复
